---
title: "Genomic Selection practice"
author: "Zhikai Yang"
date: "March 9th, 2022"
output: NULL
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```



###Visualization for public data
```{r}
library(data.table)
library(ggplot2)
library(agricolae)
library(ggpubr)

p_K10_all <- fread("largedata/prediction_accuracy_all_again.txt", data.table = F)
p_K10_normal = fread("largedata/prediction_accuracy_normal.txt",data.table = F)

p_K10 = rbind(p_K10_normal,p_K10_all)

dp <- ggplot(p_K10, aes(x=method, y=accuracy, fill=method)) + 
  geom_violin(trim=FALSE)+
  geom_boxplot(width=0.1, fill="white")+
  labs(title="Plot of Predication Accuracy by Methods",x="Method", y = "Predication Accuracy")
dp + theme_classic()

fsize =16
p <-ggplot(p_K10, aes(x=method, y=accuracy, fill=method)) +
  geom_boxplot(outlier.colour="black", outlier.shape=16, outlier.size=1, notch=FALSE) +
   xlab("Method") +
    ylab("Predication Accuracy") +
    ggtitle("Plot of Predication Accuracy by Method") +
    theme_classic() +
    labs(fill = "") +
    #scale_y_continuous(limits = c(-0.01, 1)) +
    #stat_compare_means(method = "t.test")+
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "right", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

p

t.test(p_K10$accuracy[p_K10$method=="rrBLUP_less"], p_K10$accuracy[p_K10$method=="rrBLUP_less_geno_microbiome"])

```
###Visualization for jyanglab data
```{r}

p_K10 <- fread("largedata/prediction_accuracy_trait_Canopy_Coverage_date_12-Aug_jyang.txt", data.table = F)


dp <- ggplot(p_K10, aes(x=method, y=accuracy, fill=method)) + 
  geom_violin(trim=FALSE)+
  geom_boxplot(width=0.1, fill="white")+
  labs(title="Plot of Predication Accuracy by Methods",x="Method", y = "Predication Accuracy")
dp + theme_classic()

fsize =16
p <-ggplot(p_K10, aes(x=method, y=accuracy, fill=method)) +
  geom_boxplot(outlier.colour="black", outlier.shape=16, outlier.size=1, notch=FALSE) +
   xlab("Method") +
    ylab("Predication Accuracy") +
    ggtitle("Plot of Predication Accuracy by Method") +
    theme_classic() +
    labs(fill = "") +
    #scale_y_continuous(limits = c(-0.01, 1)) +
    #stat_compare_means(method = "t.test")+
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "right", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

p

t.test(p_K10$accuracy[p_K10$method=="rrBLUP"], p_K10$accuracy[p_K10$method=="rrBLUP_geno_microbiome"])

```


#all vegetation indexes visualization
```{r}
pred_all_vis_dates = fread("largedata/pred_all_vis_dates.txt", data.table = F)
pred_all_vis_dates$date <- factor(pred_all_vis_dates$date, levels = c( "6-Jul", "12-Aug", "14-Aug", "16-Aug", "20-Aug", "22-Aug", "23-Aug", "26-Aug", "30-Aug", "1-Sep", "3-Sep", "5-Sep"),
                    labels =c( "6-Jul", "12-Aug", "14-Aug", "16-Aug", "20-Aug", "22-Aug", "23-Aug", "26-Aug", "30-Aug", "1-Sep", "3-Sep", "5-Sep"))

id_pc = which(pred_all_vis_dates$method == "rrBLUP_PC_microbiome")
pred_all_vis_dates = pred_all_vis_dates[-id_pc,]

vis = as.character(data.frame(table(pred_all_vis_dates$trait))$Var1)

plist = list()

for (i in 1:9) {
    plist[[i]] = ggboxplot(pred_all_vis_dates[which(pred_all_vis_dates$trait == vis[i]),], x = "date", y = "accuracy", color = "method", palette = "jco",add = "jitter") + 
    xlab("") +
    ylab("Prediction Accuracy ") +
    ggtitle(vis[i]) +
    theme_classic() +
    labs(fill = "") +
    scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 25, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

    
}


library(ggpubr)
figure <- ggarrange(plist[[1]], plist[[2]],plist[[3]],plist[[4]],plist[[5]],plist[[6]],plist[[7]],plist[[8]],plist[[9]], ncol = 3, nrow = 3)
figure


```
#on HCC
```{r}
f <- list.files(path="largedata", pattern="prediction_accuracy_seed", full.names = T)

out <- data.frame()
for(i in 1:length(f)){
  tem <- fread(f[i], header=TRUE)
  tem$file <- f[i]
  out <- rbind(out, tem)
}

out$trait  <- gsub(".*trait_|_date.*", "", out$file)

id_pc = which(out$method == "rrBLUP_PC_microbiome")
out = out[-id_pc,]
fwrite(out[,-7], "largedata/pred_canopy_dates_seeds.txt", sep = "\t", quote = F, row.names = F, col.names = T)



```
#on local

```{r}
pred_canopy = fread("largedata/pred_canopy_dates_seeds.txt", data.table = F)

pred_canopy_avg =  as.data.frame( pred_canopy %>% group_by(trait, date, method, seed) %>% summarise_all(mean))


pred_canopy_avg$date <- factor(pred_canopy_avg$date, levels = c( "July6", "Aug12", "Sept5"), labels =c( "Jul-6", "Aug-12", "Sep-5"))


fsize = 18
p <- ggboxplot(pred_canopy_avg, x = "date", y = "accuracy",
          color = "method", palette = "jco",
          add = "jitter")
p_date = p + stat_compare_means(aes(group = method), label = "p.signif", paired = T)+
  xlab("Date") +
    ylab("Prediction Accuracy ") +
    ggtitle("") +
    theme_classic() +
    labs(fill = "") +
    #scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

pdf("graphs/prediction_accuracy_canopy_coverage_by_dates.pdf", width = 9, height= 6)
p_date
dev.off()
```

